apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong
        ports:
        - containerPort: 8000
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/usr/local/kong/declarative/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        volumeMounts:
        - mountPath: /usr/local/kong/declarative/kong.yml
          name: kong-config
      volumes:
      - name: kong-config
        hostPath:
          path: /data/kong/kong.yml


---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  selector:
    app: kong
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
