apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-client
  template:
    metadata:
      labels:
        app: ws-client
    spec: 
      containers:
      - name: ws-client
        image: ws-client:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ws-client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ws-client
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
